name: Publish apk

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and publish apk
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build app
        run: gradle --no-daemon wrapper --gradle-version 8.0 && ./gradlew --no-daemon assembleRelease

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./app/build/outputs/apk/release/app-release.apk
          asset_name: FavoritesImmortalizer-$tag.apk
